server:
  port: 80


plate:
  password: qqhru
  url: http://123.207.7.203:8081
  num: gjl
spring:
  datasource:
    name: gjl
    url: jdbc:mysql://127.0.0.1:3306/weixingjl?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5





## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.gjl.graduation.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  config: classpath:logback/logback.xml
